In [35]:
import pandas as pd
import numpy as np


data=pd.read_excel('C:/Users/dps/Desktop/data/data.xlsx') #Include your data file instead of data.xlsx
idea=data.iloc[:,0:1] #Selecting the first column that has text.

#corpus=[]
#for index,row in idea.iterrows():
#    corpus.append(row['Idea']
                  
#Converting the column of data from excel sheet into a list of documents, where each document corresponds to a group of sentences.
corpus=['She went to the airport to see him off.','I prefer reading to writing.',
        'Los Angeles is in California. It is southeast of San Francisco.'
        ,'I ate a burger then went to bed.','Compare your answer with Tom.',
        'I had hardly left home when it began to rain heavily.',
        'If he had asked me, I would have given it to him. ',
        'I could have come by auto, but who would pay the fare? ',
        'Whatever it may be, you should not have beaten him.',
        'You should have told me yesterday','I should have joined this course last year.',
        'Where are you going?','There are too many people here.','Everyone always asks me that.',       
        'I did not think you were going to make it.','Be quiet while I am speaking.','I can not figure out why he said so.']


In [42]:
#Count Vectoriser then tidf transformer

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['airport', 'always', 'am', 'angeles', 'answer', 'are', 'asked', 'asks', 'ate', 'auto', 'be', 'beaten', 'bed', 'began', 'burger', 'but', 'by', 'california', 'can', 'come', 'compare', 'could', 'course', 'did', 'everyone', 'fare', 'figure', 'francisco', 'given', 'going', 'had', 'hardly', 'have', 'he', 'heavily', 'here', 'him', 'home', 'if', 'in', 'is', 'it', 'joined', 'last', 'left', 'los', 'make', 'many', 'may', 'me', 'not', 'of', 'off', 'out', 'pay', 'people', 'prefer', 'quiet', 'rain', 'reading', 'said', 'san', 'see', 'she', 'should', 'so', 'southeast', 'speaking', 'that', 'the', 'then', 'there', 'think', 'this', 'to', 'told', 'tom', 'too', 'went', 'were', 'whatever', 'when', 'where', 'while', 'who', 'why', 'with', 'would', 'writing', 'year', 'yesterday', 'you', 'your']
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [40]:
X.shape

(17, 93)

In [45]:
from sklearn.feature_extraction.text import TfidfTransformer

transformer = TfidfTransformer(smooth_idf=False)
tfidf = transformer.fit_transform(X)
print(tfidf.toarray())                        


[[0.37835527 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.25620815 0.        ]
 [0.         0.         0.46269305 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [47]:
from sklearn.cluster import KMeans

num_clusters = 3 #Change it according to your data.
km = KMeans(n_clusters=num_clusters)
km.fit(tfidf)
clusters = km.labels_.tolist()
idea={'Idea':corpus, 'Cluster':clusters} #Creating dict having doc with the corresponding cluster number.
frame=pd.DataFrame(idea,index=[clusters], columns=['Idea','Cluster']) # Converting it into a dataframe.

print("\n")
print(frame) #Print the doc with the labeled cluster number.
print("\n")
print(frame['Cluster'].value_counts()) #Print the counts of doc belonging to each cluster.



                                                Idea  Cluster
1            She went to the airport to see him off.        1
1                       I prefer reading to writing.        1
0  Los Angeles is in California. It is southeast ...        0
1                   I ate a burger then went to bed.        1
2                      Compare your answer with Tom.        2
0  I had hardly left home when it began to rain h...        0
2  If he had asked me, I would have given it to h...        2
2  I could have come by auto, but who would pay t...        2
2  Whatever it may be, you should not have beaten...        2
2                  You should have told me yesterday        2
2        I should have joined this course last year.        2
0                               Where are you going?        0
0                    There are too many people here.        0
2                      Everyone always asks me that.        2
0         I did not think you were going to make it.        0
2     